{{- define "eric-oss-task-automation-ae.labels" }}
app.kubernetes.io/name: {{ template "eric-oss-task-automation-ae.name" . }}
app.kubernetes.io/version: {{ template "eric-oss-task-automation-ae.version" . }}
app.kubernetes.io/instance: {{ .Release.Name | quote }}
app: {{ template "eric-oss-task-automation-ae.name" . }}
chart: {{ template "eric-oss-task-automation-ae.chart" . }}
release: {{ .Release.Name | quote }}
heritage: {{ .Release.Service | quote }}
{{- end}}
