{{- $serviceMesh := include "eric-oss-task-automation-ae.service-mesh.enabled" . | trim -}}
{{- $serviceMeshIngress := include "eric-oss-task-automation-ae.service-mesh-ingress.enabled" . | trim -}}
{{- if and (eq $serviceMesh "true") (eq $serviceMeshIngress "true") -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ template "eric-oss-task-automation-ae.name" . }}-gateway
  annotations:
    {{- include "eric-oss-task-automation-ae.helm-annotations" .| nindent 4 }}
    meta.helm.sh/release-name: {{ template "eric-oss-task-automation-ae.release.name" . }}
  labels:
    {{- include "eric-oss-task-automation-ae.kubernetes-io-info" .| nindent 4 }}
spec:
  selector:
    app: service-mesh-ingress-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - {{ required "A valid .Values.global.hosts.<app-name> entry required" .Values.global.hosts.ta }}
    {{- if .Values.tls.enabled }}
    tls:
     httpsRedirect: true # sends 301 redirect for http requests
    {{- end }}
  {{- if .Values.tls.enabled }}
  - port:
      name: https
      number: 443
      protocol: HTTPS
    hosts:
      - {{ required "A valid .Values.global.hosts.<app-name> entry required" .Values.global.hosts.ta }}
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: {{ required "A valid .Values.tls.secretName entry required" .Values.tls.secretName }}
  {{- end }}
{{ end }}
