{{- if index .Values "rbac" "enabled" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-oss-task-automation-ae.name" . }}-fa-realm-role-mapping-user-admin-configmap
  labels:
  {{- include "eric-oss-task-automation-ae.kubernetes-io-info" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-task-automation-ae.helm-annotations" . | indent 4 }}
data:
  user-realm-role-mappings.json: |
    [
      {
        "name": "UserAdmin"
      }
    ]
{{- end }}