apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-oss-task-automation-ae.name" . }}-{{ template "eric-oss-task-automation-ae.privileged.cluster.role.name" . }}-psp-binding
  labels:
  {{- include "eric-oss-task-automation-ae.kubernetes-io-info" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-task-automation-ae.helm-annotations" . | indent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "eric-oss-task-automation-ae.privileged.cluster.role.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-oss-task-automation-ae.name" . }}-sa