{{- $serviceMesh := include "eric-oss-task-automation-ae.service-mesh.enabled" . | trim -}}
{{- $tls := include "eric-oss-task-automation-ae.global-security-tls-enabled" . | trim -}}
{{- $namespace := printf "%s" .Release.Namespace -}}
{{- if and (eq $serviceMesh "true") (eq $tls "true") -}}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ template "eric-oss-task-automation-ae.name" . }}-flow-automation-db-pg-envoyfilter
  annotations:
    {{- include "eric-oss-task-automation-ae.helm-annotations" .| nindent 4 }}
    meta.helm.sh/release-name: {{ template "eric-oss-task-automation-ae.release.name" . }}
  labels:
    {{- include "eric-oss-task-automation-ae.kubernetes-io-info" .| nindent 4 }}
spec:
  workloadSelector:
   labels:
     app: eric-oss-flow-automation
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND # will match outbound listeners in all sidecars
      listener:
        portNumber: 5432
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
        name: "envoy.filters.network.postgres_proxy"
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy
          stat_prefix: postgres
          upstream_ssl: REQUIRE
  - applyTo: CLUSTER
    match:
      cluster:
        portNumber: 5432
        service: eric-oss-flow-automation-db-pg.{{ $namespace }}.svc.cluster.local
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.starttls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.UpstreamStartTlsConfig
            tls_socket_config:
              allow_renegotiation: true
              common_tls_context:
                tls_certificate_sds_secret_configs:
                - name: 'file-cert:/etc/istio/tls/flow-automation-db-pg/cert.pem~/etc/istio/tls/flow-automation-db-pg/key.pem'
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      transport_api_version: V3
                      grpc_services:
                      - envoy_grpc:
                          cluster_name: sds-grpc
                      set_node_on_first_message_only: true
                    resource_api_version: V3
                combined_validation_context:
                  default_validation_context: {}
                  validation_context_sds_secret_config:
                    name: 'file-root:/etc/istio/tls-ca/cacertbundle.pem'
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        transport_api_version: V3
                        grpc_services:
                        - envoy_grpc:
                            cluster_name: sds-grpc
                        set_node_on_first_message_only: true
                      resource_api_version: V3
{{- end }}
