apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-oss-task-automation-ae.name" . }}-sa
  labels:
  {{- include "eric-oss-task-automation-ae.kubernetes-io-info" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-task-automation-ae.helm-annotations" . | indent 4 }}
automountServiceAccountToken: false