{{- if .Values.global -}}
{{- if .Values.global.networkPolicy -}}
{{- if .Values.global.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eric-oss-task-automation-ae.name" . }}-default-deny-ingress
  labels:
    {{- include "eric-oss-task-automation-ae.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-task-automation-ae.product-info" . | nindent 4 }}    
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
{{- end }}
{{- end }}