#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if index .Values "api-gateway-route" "enabled" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "eric-oss-task-automation-ae.name" . }}-flow-automation-creates-route-hook
  labels:
    {{- include "eric-oss-task-automation-ae.kubernetes-io-info" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    {{- include "eric-oss-task-automation-ae.helm-annotations" . | indent 4 }}
spec:
  backoffLimit: 8
  template:
    spec:
      serviceAccountName: {{ template "eric-oss-task-automation-ae.name" . }}-sa
      {{- if include "eric-oss-task-automation-ae.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ include "eric-oss-task-automation-ae.pullSecrets" . }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: api-gateway-client
          image: {{ template "eric-oss-task-automation-ae.imagePath" (dict "imageId" "api-gateway-client" "values" .Values "files" .Files) }}
          imagePullPolicy: {{ include "eric-oss-task-automation-ae.registryImagePullPolicy" .}}
          env:
          - name: SYSTEM_USER
            valueFrom:
              secretKeyRef:
                name: {{ index .Values "api-gateway-route" "credentials" "name" }}
                key: {{ index .Values "api-gateway-route" "credentials" "user-key" }}
          - name: SYSTEM_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ index .Values "api-gateway-route" "credentials" "name" }}
                key: {{ index .Values "api-gateway-route" "credentials" "pwd-key" }}
          args:
          - "{{ index .Values "api-gateway-route" "route-path" "tag" }}"
          - "https://{{ index .Values "global" "hosts" "gas" }}"
          - "$(SYSTEM_USER)"
          - "$(SYSTEM_USER_PASSWORD)"
          - "upgrade"
          - "/config/route.json"
          volumeMounts:
          - name: {{ template "eric-oss-task-automation-ae.name" . }}-fa-route-configuration-volume
            mountPath: /config
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 7373585
            capabilities:
              drop:
                - "all"
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: {{ template "eric-oss-task-automation-ae.name" . }}-fa-route-configuration-volume
        configMap:
          name: {{ template "eric-oss-task-automation-ae.name" . }}-flow-automation-route-configmap
          defaultMode: 0777
{{- end }}
